// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/bitbom.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestSBOMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SbomPath string `protobuf:"bytes,1,opt,name=sbom_path,json=sbomPath,proto3" json:"sbom_path,omitempty"`
}

func (x *IngestSBOMRequest) Reset() {
	*x = IngestSBOMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestSBOMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSBOMRequest) ProtoMessage() {}

func (x *IngestSBOMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSBOMRequest.ProtoReflect.Descriptor instead.
func (*IngestSBOMRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{0}
}

func (x *IngestSBOMRequest) GetSbomPath() string {
	if x != nil {
		return x.SbomPath
	}
	return ""
}

type IngestSBOMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IngestSBOMResponse) Reset() {
	*x = IngestSBOMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestSBOMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSBOMResponse) ProtoMessage() {}

func (x *IngestSBOMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSBOMResponse.ProtoReflect.Descriptor instead.
func (*IngestSBOMResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{1}
}

func (x *IngestSBOMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{2}
}

type CacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{3}
}

func (x *CacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IngestOSVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsvPath string `protobuf:"bytes,1,opt,name=osv_path,json=osvPath,proto3" json:"osv_path,omitempty"`
}

func (x *IngestOSVRequest) Reset() {
	*x = IngestOSVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestOSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestOSVRequest) ProtoMessage() {}

func (x *IngestOSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestOSVRequest.ProtoReflect.Descriptor instead.
func (*IngestOSVRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{4}
}

func (x *IngestOSVRequest) GetOsvPath() string {
	if x != nil {
		return x.OsvPath
	}
	return ""
}

type IngestOSVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IngestOSVResponse) Reset() {
	*x = IngestOSVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestOSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestOSVResponse) ProtoMessage() {}

func (x *IngestOSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestOSVResponse.ProtoReflect.Descriptor instead.
func (*IngestOSVResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{5}
}

func (x *IngestOSVResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryString string `protobuf:"bytes,1,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRequest) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dependencies []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{7}
}

func (x *QueryResponse) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type AllKeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllKeysRequest) Reset() {
	*x = AllKeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKeysRequest) ProtoMessage() {}

func (x *AllKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKeysRequest.ProtoReflect.Descriptor instead.
func (*AllKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{8}
}

type AllKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *AllKeysResponse) Reset() {
	*x = AllKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllKeysResponse) ProtoMessage() {}

func (x *AllKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllKeysResponse.ProtoReflect.Descriptor instead.
func (*AllKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{9}
}

func (x *AllKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CustomLeaderboardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Script string `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
}

func (x *CustomLeaderboardRequest) Reset() {
	*x = CustomLeaderboardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomLeaderboardRequest) ProtoMessage() {}

func (x *CustomLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*CustomLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{10}
}

func (x *CustomLeaderboardRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type CustomLeaderboardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*LeaderboardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *CustomLeaderboardResponse) Reset() {
	*x = CustomLeaderboardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomLeaderboardResponse) ProtoMessage() {}

func (x *CustomLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*CustomLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{11}
}

func (x *CustomLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WeightedNACDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Script string `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
}

func (x *WeightedNACDRequest) Reset() {
	*x = WeightedNACDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightedNACDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedNACDRequest) ProtoMessage() {}

func (x *WeightedNACDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedNACDRequest.ProtoReflect.Descriptor instead.
func (*WeightedNACDRequest) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{12}
}

func (x *WeightedNACDRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type WeightedNACDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*LeaderboardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *WeightedNACDResponse) Reset() {
	*x = WeightedNACDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightedNACDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedNACDResponse) ProtoMessage() {}

func (x *WeightedNACDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedNACDResponse.ProtoReflect.Descriptor instead.
func (*WeightedNACDResponse) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{13}
}

func (x *WeightedNACDResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{14}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dependency) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	QueryLength int32  `protobuf:"varint,3,opt,name=query_length,json=queryLength,proto3" json:"query_length,omitempty"`
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bitbom_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitbom_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_bitbom_proto_rawDescGZIP(), []int{15}
}

func (x *LeaderboardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LeaderboardEntry) GetQueryLength() int32 {
	if x != nil {
		return x.QueryLength
	}
	return 0
}

var File_proto_bitbom_proto protoreflect.FileDescriptor

var file_proto_bitbom_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x22, 0x30, 0x0a, 0x11,
	0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x42, 0x4f, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x62, 0x6f, 0x6d, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x62, 0x6f, 0x6d, 0x50, 0x61, 0x74, 0x68, 0x22, 0x2e,
	0x0a, 0x12, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x42, 0x4f, 0x4d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0e,
	0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x29,
	0x0a, 0x0d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x49, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x4f, 0x53, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x73, 0x76, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x73, 0x76, 0x50, 0x61, 0x74, 0x68, 0x22, 0x2d, 0x0a, 0x11, 0x49, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x4f, 0x53, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x47, 0x0a, 0x0d, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x64,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x32, 0x0a, 0x18,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x22, 0x4f, 0x0a, 0x19, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x2d, 0x0a, 0x13, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x4e, 0x41, 0x43,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x22, 0x4a, 0x0a, 0x14, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x4e, 0x41, 0x43, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x69, 0x74, 0x62,
	0x6f, 0x6d, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x0a,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x5d, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x32, 0xcd, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x42,
	0x4f, 0x4d, 0x12, 0x19, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x53, 0x42, 0x4f, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x42, 0x4f,
	0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x14, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f,
	0x6d, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x4f, 0x53, 0x56, 0x12, 0x18, 0x2e, 0x62,
	0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x4f, 0x53, 0x56, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e,
	0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x4f, 0x53, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xb1, 0x02, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x40, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x73, 0x12,
	0x16, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d,
	0x2e, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x58, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x20, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d,
	0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x4e, 0x41, 0x43, 0x44, 0x12, 0x1b, 0x2e, 0x62, 0x69, 0x74,
	0x62, 0x6f, 0x6d, 0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x4e, 0x41, 0x43, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x69, 0x74, 0x62, 0x6f, 0x6d,
	0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x4e, 0x41, 0x43, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x74, 0x2d, 0x62, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x65,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x69, 0x74, 0x62,
	0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bitbom_proto_rawDescOnce sync.Once
	file_proto_bitbom_proto_rawDescData = file_proto_bitbom_proto_rawDesc
)

func file_proto_bitbom_proto_rawDescGZIP() []byte {
	file_proto_bitbom_proto_rawDescOnce.Do(func() {
		file_proto_bitbom_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bitbom_proto_rawDescData)
	})
	return file_proto_bitbom_proto_rawDescData
}

var file_proto_bitbom_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_bitbom_proto_goTypes = []any{
	(*IngestSBOMRequest)(nil),         // 0: bitbom.IngestSBOMRequest
	(*IngestSBOMResponse)(nil),        // 1: bitbom.IngestSBOMResponse
	(*CacheRequest)(nil),              // 2: bitbom.CacheRequest
	(*CacheResponse)(nil),             // 3: bitbom.CacheResponse
	(*IngestOSVRequest)(nil),          // 4: bitbom.IngestOSVRequest
	(*IngestOSVResponse)(nil),         // 5: bitbom.IngestOSVResponse
	(*QueryRequest)(nil),              // 6: bitbom.QueryRequest
	(*QueryResponse)(nil),             // 7: bitbom.QueryResponse
	(*AllKeysRequest)(nil),            // 8: bitbom.AllKeysRequest
	(*AllKeysResponse)(nil),           // 9: bitbom.AllKeysResponse
	(*CustomLeaderboardRequest)(nil),  // 10: bitbom.CustomLeaderboardRequest
	(*CustomLeaderboardResponse)(nil), // 11: bitbom.CustomLeaderboardResponse
	(*WeightedNACDRequest)(nil),       // 12: bitbom.WeightedNACDRequest
	(*WeightedNACDResponse)(nil),      // 13: bitbom.WeightedNACDResponse
	(*Dependency)(nil),                // 14: bitbom.Dependency
	(*LeaderboardEntry)(nil),          // 15: bitbom.LeaderboardEntry
}
var file_proto_bitbom_proto_depIdxs = []int32{
	14, // 0: bitbom.QueryResponse.dependencies:type_name -> bitbom.Dependency
	15, // 1: bitbom.CustomLeaderboardResponse.entries:type_name -> bitbom.LeaderboardEntry
	15, // 2: bitbom.WeightedNACDResponse.entries:type_name -> bitbom.LeaderboardEntry
	0,  // 3: bitbom.CommandService.IngestSBOM:input_type -> bitbom.IngestSBOMRequest
	2,  // 4: bitbom.CommandService.Cache:input_type -> bitbom.CacheRequest
	4,  // 5: bitbom.CommandService.IngestOSV:input_type -> bitbom.IngestOSVRequest
	6,  // 6: bitbom.QueryService.QueryDependencies:input_type -> bitbom.QueryRequest
	8,  // 7: bitbom.QueryService.AllKeys:input_type -> bitbom.AllKeysRequest
	10, // 8: bitbom.QueryService.CustomLeaderboard:input_type -> bitbom.CustomLeaderboardRequest
	12, // 9: bitbom.QueryService.WeightedNACD:input_type -> bitbom.WeightedNACDRequest
	1,  // 10: bitbom.CommandService.IngestSBOM:output_type -> bitbom.IngestSBOMResponse
	3,  // 11: bitbom.CommandService.Cache:output_type -> bitbom.CacheResponse
	5,  // 12: bitbom.CommandService.IngestOSV:output_type -> bitbom.IngestOSVResponse
	7,  // 13: bitbom.QueryService.QueryDependencies:output_type -> bitbom.QueryResponse
	9,  // 14: bitbom.QueryService.AllKeys:output_type -> bitbom.AllKeysResponse
	11, // 15: bitbom.QueryService.CustomLeaderboard:output_type -> bitbom.CustomLeaderboardResponse
	13, // 16: bitbom.QueryService.WeightedNACD:output_type -> bitbom.WeightedNACDResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_bitbom_proto_init() }
func file_proto_bitbom_proto_init() {
	if File_proto_bitbom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bitbom_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IngestSBOMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IngestSBOMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*IngestOSVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*IngestOSVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AllKeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*AllKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CustomLeaderboardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CustomLeaderboardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*WeightedNACDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*WeightedNACDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bitbom_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*LeaderboardEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bitbom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_bitbom_proto_goTypes,
		DependencyIndexes: file_proto_bitbom_proto_depIdxs,
		MessageInfos:      file_proto_bitbom_proto_msgTypes,
	}.Build()
	File_proto_bitbom_proto = out.File
	file_proto_bitbom_proto_rawDesc = nil
	file_proto_bitbom_proto_goTypes = nil
	file_proto_bitbom_proto_depIdxs = nil
}
